In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
train_data = pd.read_csv('Google_Stock_Price_Train.csv')
test_data = pd.read_csv('Google_Stock_Price_Test.csv')

In [ ]:
train_data

Date    Open    High     Low   Close      Volume
0       3/1/2012  325.25  332.83  324.97  663.59   7380500.0
1       4/1/2012  331.27  333.87  329.08  666.45   5749400.0
2       5/1/2012  329.83  330.75  326.89  657.21   6590300.0
3       6/1/2012  328.34  328.77  323.68  648.24   5405900.0
4       9/1/2012  322.04  322.29  309.46  620.76  11688800.0
...          ...     ...     ...     ...     ...         ...
1253  12/23/2016  790.90  792.74  787.28  789.91    623400.0
1254  12/27/2016  790.68  797.86  787.66  791.55    789100.0
1255  12/28/2016  793.70  794.23  783.20  785.05   1153800.0
1256  12/29/2016  783.33  785.93  778.92  782.79    744300.0
1257  12/30/2016  782.75  782.78  770.41  771.82   1770000.0

[1258 rows x 6 columns]

In [ ]:
train_data.shape

(1258, 6)

In [ ]:
train_data.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [ ]:
train_data.dtypes

Date       object
Open      float64
High      float64
Low       float64
Close     float64
Volume    float64
dtype: object

In [ ]:
X_train = train_data[['Open','High','Low','Volume']].values
print(X_train)

[[3.2525e+02 3.3283e+02 3.2497e+02 7.3805e+06]
 [3.3127e+02 3.3387e+02 3.2908e+02 5.7494e+06]
 [3.2983e+02 3.3075e+02 3.2689e+02 6.5903e+06]
 ...
 [7.9370e+02 7.9423e+02 7.8320e+02 1.1538e+06]
 [7.8333e+02 7.8593e+02 7.7892e+02 7.4430e+05]
 [7.8275e+02 7.8278e+02 7.7041e+02 1.7700e+06]]


In [ ]:
y_train = train_data.iloc[:,4:5].values
print(y_train)

[[663.59]
 [666.45]
 [657.21]
 ...
 [785.05]
 [782.79]
 [771.82]]


In [ ]:
print(X_train.shape)
print(y_train.shape)

(1258, 4)
(1258, 1)


In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
test_data
X_test = test_data[['Open','High','Low','Volume']].values
y_test = test_data.iloc[:,4:5].values
y_test

array([[786.14],
       [786.9 ],
       [794.02],
       [806.15],
       [806.65],
       [804.79],
       [807.91],
       [806.36],
       [807.88],
       [804.61],
       [806.07],
       [802.17],
       [805.02],
       [819.31],
       [823.87],
       [835.67],
       [832.15],
       [823.31],
       [802.32],
       [796.79]])

In [ ]:
y_pred = regressor.predict(X_test)
y_pred

array([[754.40588319],
       [798.71235287],
       [795.07824942],
       [743.57927405],
       [829.4820455 ],
       [842.971888  ],
       [824.66560288],
       [819.38288804],
       [853.16453882],
       [836.00568628],
       [850.32137505],
       [809.50764   ],
       [865.09686812],
       [747.53742228],
       [836.37799812],
       [813.03267399],
       [868.59517571],
       [750.37950626],
       [807.90366731],
       [817.04218114]])

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt
rms_error = sqrt(mean_squared_error(y_test,y_pred))
print(f"The Root Mean Squared Error is : {rms_error} ")

The Root Mean Squared Error is : 38.11730407638581 
