In [3]:
import numpy as np


In [4]:
#creating a numpy array
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [5]:
nested_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#stopping point is not included
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#np.arange() with step size
#Here , 2 is the step size
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
#creating a array of zeros
#Here , 0. represents that the values are of floating point data type
np.zeros(3)

array([0., 0., 0.])

In [9]:
#passing the shape to the np.zeros()
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#creating an array of one
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
#creating an array of size 10 X 10 and setting the datatype of the value as "integer" rather than deafult floating point
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [13]:
#creating an identity matrix
#we are not passing shape as identity matrix will always be a square mmatrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#creating an array of random numbers
np.random.rand(2)

array([0.20085795, 0.46796239])

In [15]:
np.random.rand(3,4)

array([[0.80869819, 0.39256364, 0.7672798 , 0.87040927],
       [0.63413667, 0.72249719, 0.41596801, 0.8095738 ],
       [0.33936014, 0.31395994, 0.01189052, 0.74829466]])

In [16]:
np.random.randn(3,4)

array([[ 0.92021931, -0.70069682,  0.96910687, -0.66756682],
       [ 1.29531045, -1.39124056,  0.56638258, -1.30602192],
       [ 1.169276  , -2.89863309, -0.83027951,  1.5774419 ]])

In [18]:
#gives 10 numbers between 1 and 100
np.random.randint(1,100,10)
# If we want a matrix , just give a tuple
np.random.randint(1,100,(5,4))


array([[33, 71,  6, 77],
       [28, 92,  9, 28],
       [34,  8,  5, 11],
       [10, 38, 26, 65],
       [53, 76, 82, 28]])

In [21]:
#if we want to generate the same random value , 
# give a number in the seed function , Here ,"42"
np.random.seed(42)
np.random.rand(4)
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [22]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [23]:
arr = np.arange(25)

In [24]:
ranarr = np.random.randint(0,50,10)

In [25]:
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[43 29 37  1 20 32 11 21 43 24]


In [29]:
#reshaping an array
arr.shape
arr.reshape(5,5)
#the reshape does not affect the original array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
#getting the maximum value from the array
print(ranarr.max())
#getting the index of the maximum value from the array
print(ranarr.argmax())

43
0


In [35]:
#getting the minimum value from the array
print(ranarr.min())
#getting the index of the minimum value from the array
print(ranarr.argmin())

1
3


In [36]:
#checking the datatype of the elements of the array
ranarr.dtype

dtype('int64')

In [38]:
mylist1 = ['sonu','kumar']
newarr = np.array(mylist1)
print(newarr)
print(newarr.dtype)

['sonu' 'kumar']
<U5


# Numpy index Selection

In [40]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [42]:
#retreiving an element from a particular index
print(arr[8])
#slicing a numpy array is also same as slicing a python list
#up to but not including
print(arr[1:5])

8
[1 2 3 4]


In [43]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
#this is called broadcasting..
#it will not happen in normal python list
arr[0:5] = 100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr = np.arange(0,11)
slice_of_arr = arr[0:5]
print(slice_of_arr)
print(arr)

[0 1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [49]:
#If we change anything in the slice of the array,
#It will also affect the original arr
slice_of_arr[:]  =  99
print(slice_of_arr)
print(arr)

[99 99 99 99 99]
[99 99 99 99 99  5  6  7  8  9 10]


In [53]:
#To avoid this the above situation , We use the copy function while copying a full array or part of it
arr_copy = arr.copy()
print(arr_copy)
arr_copy[:] = 100
print(arr_copy)
print(arr)

[99 99 99 99 99  5  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99  5  6  7  8  9 10]


In [55]:
arr_part_copy = arr[2:5].copy()
print(arr_part_copy)
arr_part_copy[:] = 0
print(arr_part_copy)
print(arr)

[99 99 99]
[0 0 0]
[99 99 99 99 99  5  6  7  8  9 10]


In [61]:
arr_2d = np.array([[5,10,15],[20,25,30],[30,35,40]])
print(arr_2d)
#retreiving a particular element from the np array is same as python
print(arr_2d[0][1])
#Another Way
print(arr_2d[0,1])
print(f"the shape of the matrix created is : {arr_2d.shape}")

[[ 5 10 15]
 [20 25 30]
 [30 35 40]]
10
10
the shape of the matrix created is : (3, 3)


In [60]:
arr = np.arange(1,11)

In [63]:
#conditional checking
#check for all elements in the numpy array for which value is greater than 4
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [66]:
#returns only those values where bool_arr value is True
bool_arr = arr > 4
arr[bool_arr]
#in one step
print(arr[arr > 4])

[ 5  6  7  8  9 10]


# NumPy Operations

In [69]:
arr =  np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
#Adding a value to the array will add the value to each element as follows:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
#For this to work , arr has to be of same shape
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
#Multiplication of Two Array
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [73]:
#Division of two array
# 0 / 0 or any number divided  by zero will output as "nan" :- not a number by numpy 
# And also gives a warning
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
#Square root of every number in the array
print(np.sqrt(arr))
#Taking Sin value of every element of the array
print(np.sin(arr))
#Taking natural log of every element of the array
print(np.log(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


In [76]:
print(arr.sum())
print(arr.max())
print(arr.mean())

45
9
4.5


In [78]:
arr_2d = np.arange(0,25).reshape(5,5)
print(arr_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [79]:
#Using Numpy operations on the 2D array
print(arr_2d.sum())
print(arr_2d + 5)

300
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [81]:
#Sum of all rows and all the column
#By the use of the axis, Rows = (Axis = 0)
#Column = (Axis = 1)
print(arr_2d.sum(axis = 0))
print(arr_2d.sum(axis = 1))

[50 55 60 65 70]
[ 10  35  60  85 110]
